#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = ["markdown-it-py>=4"]
# ///
"""Emit the SRD conditions, both editions, as our EDN data files.

Usage: emit-conditions.py OPEN5E_CLONE SRD52_WORKTREE

Reads the corrected open5e data (the open5e-api clone, branch srd-corrections) and writes
  SRD52_WORKTREE/resources/public/srd/2014/conditions.edn
  SRD52_WORKTREE/resources/public/srd/2024/conditions.edn

Text stays verbatim; only structure changes. Each condition's :body uses the block format in
srd_format.py (paragraphs, lists, tables; 2024's bullet labels in bold), with links to the other
conditions marked. Pages come from the readable SRD transcripts in SRD52_WORKTREE/resources/srd/.

Refuses to write if the text changes in conversion (spacing and markdown markers aside).
"""
import json, re, subprocess, sys
from pathlib import Path

EDITIONS = {
    2014: {'dir': 'srd-2014', 'document': 'SRD 5.1', 'transcript': 'SRD-5.1.readable.txt',
           'labelled': False,
           'attribution': ('This work includes material taken from the System Reference Document 5.1 '
                           '(“SRD 5.1”) by Wizards of the Coast LLC and available at '
                           'https://dnd.wizards.com/resources/systems-reference-document. The SRD 5.1 is '
                           'licensed under the Creative Commons Attribution 4.0 International License '
                           'available at https://creativecommons.org/licenses/by/4.0/legalcode.')},
    2024: {'dir': 'srd-2024', 'document': 'SRD 5.2.1', 'transcript': 'SRD-5.2.1.readable.txt',
           'labelled': True,
           'attribution': ('This work includes material from the System Reference Document 5.2.1 '
                           '(“SRD 5.2.1”) by Wizards of the Coast LLC, available at '
                           'https://www.dndbeyond.com/srd. The SRD 5.2.1 is licensed under the Creative '
                           'Commons Attribution 4.0 International License, available at '
                           'https://creativecommons.org/licenses/by/4.0/legalcode.')},
}
sys.path.insert(0, str(Path(__file__).parent))
import srd_format as F


def page_of(transcript, name, edition):
    t = transcript
    if edition == 2014:
        start = t.index('Appendix PH-A:')
        m = re.compile(r'^' + re.escape(name) + r'$', re.M).search(t, start)
    else:
        m = re.compile(r'^' + re.escape(name) + r' \[Condition\]$', re.M).search(t)
    assert m, f'{name}: heading not found in the {edition} transcript'
    return int(re.findall(r'<<<PAGE (\d+)>>>', t[:m.start()])[-1])

def main(clone, srd52):
    clone, srd52 = Path(clone), Path(srd52)
    rev = subprocess.run(['git', '-C', str(clone), 'rev-parse', '--short', 'HEAD'],
                         capture_output=True, text=True).stdout.strip()
    for ed, cfg in EDITIONS.items():
        recs = json.load(open(clone / 'data/v2/wizards-of-the-coast' / cfg['dir'] / 'ConditionDescription.json',
                              encoding='utf-8'))
        transcript = open(srd52 / 'resources/srd' / cfg['transcript'], encoding='utf-8').read()
        conds = []
        links = F.Links()
        for r in sorted(recs, key=lambda r: r['fields']['describes']):
            key, desc = r['fields']['describes'], r['fields']['desc']
            name = key.capitalize()
            blocks = F.parse(desc, links, ('condition', key), cfg['labelled'])
            src = ''.join(w for line in desc.split('\n') for w in F.plain_source(line, links))
            got = ''.join(F.block_words(blocks))
            assert got == src, f'{ed} {key}: text changed in conversion'
            conds.append({'key': F.Kw(key), 'name': name, 'page': page_of(transcript, name, ed), 'body': blocks})
        data = {'srd/document': cfg['document'], 'srd/edition': ed, 'srd/license': 'CC BY 4.0',
                'srd/attribution': cfg['attribution'], 'conditions': conds}
        body = F.edn(F.keywordize(data)).replace(' :conditions [{', '\n :conditions\n [{').replace('} {:key', '}\n  {:key')
        lines = [f';; Generated by scripts/srd/emit-conditions.py (agents/develop) from open5e-api',
                 f';; srd-corrections {rev}. Do not edit: fix the source and regenerate.', body]
        out = srd52 / f'resources/public/srd/{ed}/conditions.edn'
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text('\n'.join(lines) + '\n', encoding='utf-8')
        print(f'  {out}: {len(conds)} conditions, pages {min(c["page"] for c in conds)}-{max(c["page"] for c in conds)}, '
              f'{body.count("[:a {")} links')

if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
