const { chromium } = require('playwright'); const fs = require('fs');
const EXE = ['/opt/pw-browsers/chromium-1194/chrome-linux/chrome', '/opt/pw-browsers/chromium/chrome-linux/chrome'].find(p => fs.existsSync(p));
let fails = 0; const check = (ok, m) => { console.log((ok ? 'PASS ' : 'FAIL ') + m); if (!ok) fails++; };
(async () => { const b = await chromium.launch({ executablePath: EXE }); const p = await (await b.newContext({ viewport: { width: 1300, height: 1000 } })).newPage();
  const errs = []; p.on('pageerror', e => errs.push(String(e)));
  await p.goto('file://' + process.env.LOOM); await p.setInputFiles('#file', process.env.PACKZIP);
  await p.waitForFunction(() => !document.getElementById('save').disabled, null, { timeout: 120000 });
  const card = () => p.locator('.card', { hasText: 'L4_hair_front_01.png' });
  await card().locator('.fill-btn').click();
  const ed = () => card().locator('.fill-editor');
  // count green-tinted pixels inside the drawn piece (not the pure green background)
  const tint = () => ed().locator('canvas').evaluate(c => { const d = c.getContext('2d').getImageData(0, 0, c.width, c.height).data; let n = 0;
    for (let i = 0; i < d.length; i += 4) { const r = d[i], g = d[i+1], bl = d[i+2]; if (g > 200 && r > 60 && r < 235 && g - r > 15 && Math.abs(r - bl) < 25) n++; } return n; });
  const bgIs = () => ed().locator('canvas').evaluate(c => Array.from(c.getContext('2d').getImageData(1, 1, 1, 1).data.slice(0, 3)).join(','));
  await ed().locator('.fill-row .chip', { hasText: 'Before' }).click();
  await ed().locator('label', { hasText: 'Show leaks' }).locator('input').check();
  check(await bgIs() === '0,255,0', 'Show leaks puts the piece over bright green');
  const before = await tint();
  await ed().locator('.fill-row .chip', { hasText: 'After' }).click();
  const after = await tint();
  check(before > 200, 'Before: the raw crown leaks plainly (' + before + ' tinted px on screen)');
  check(after < before, 'After shows fewer leaks (' + after + ')');
  await ed().screenshot({ path: process.env.OUT + '/leakview-after.png' });
  await ed().locator('.fill-row .chip', { hasText: 'Before' }).click(); await ed().screenshot({ path: process.env.OUT + '/leakview-before.png' });
  check(await ed().locator('input[type=color]').isDisabled(), 'the background picker is off while it shows');
  await ed().locator('label', { hasText: 'Show leaks' }).locator('input').uncheck();
  check(await bgIs() !== '0,255,0', 'and unticking brings the chosen background back');
  check(errs.length === 0, 'no page errors ' + errs.join(' | '));
  await b.close(); process.exit(fails ? 1 : 0); })();
