const { chromium, devices } = require('playwright'); const fs = require('fs');
const EXE = ['/opt/pw-browsers/chromium-1194/chrome-linux/chrome', '/opt/pw-browsers/chromium/chrome-linux/chrome'].find(p => fs.existsSync(p));
let fails = 0; const check = (ok, m) => { console.log((ok ? 'PASS ' : 'FAIL ') + m); if (!ok) fails++; };
(async () => { const b = await chromium.launch({ executablePath: EXE });
  const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
  const p = await ctx.newPage(); const errs = []; p.on('pageerror', e => errs.push(String(e)));
  await p.goto('file://' + process.env.LOOM);
  check(await p.inputValue('#ver') === 'v1.6', `pack version starts at the bundled placements' pack (${await p.inputValue('#ver')} ${await p.locator('#ver-from').textContent()})`);
  await p.setInputFiles('#file', process.env.PACKZIP);
  await p.waitForFunction(() => document.querySelectorAll('canvas.iris-canvas').length >= 3, null, { timeout: 120000 });
  check(await p.inputValue('#ver') === 'v1.6', `the v1.3 zip's own manifest does not override it (${await p.inputValue('#ver')})`);
  await p.screenshot({ path: process.env.OUT + '/m-all.png' });
  check(await p.locator('#viewbar .chip').count() > 3, 'a view bar with chips appears');
  check(await p.evaluate(() => document.body.classList.contains('compact')), 'compact cards by default on a phone');
  const before = await p.evaluate(() => document.documentElement.scrollHeight);
  await p.locator('#viewbar .chip', { hasText: 'Eyes' }).click();
  const cards = await p.locator('.card').count();
  check(cards === 3, `Eyes shows just the eye pieces (${cards} cards)`);
  const topOfFirstEditor = await p.locator('canvas.iris-canvas').first().evaluate(e => e.getBoundingClientRect().top + window.scrollY);
  check(true, `first eye editor starts ${Math.round(topOfFirstEditor)}px down the page (was the full page of ${before}px to scroll through)`);
  await p.screenshot({ path: process.env.OUT + '/m-eyes.png' });
  check(await p.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), 'no sideways scrolling');
  check(!(await p.locator('#kit-panel').evaluate(d => d.open)), 'the commission kit starts folded');
  // typing a pack version wins
  await p.locator('#settings-panel summary').click().catch(() => {});
  if (!(await p.locator('#settings-panel').evaluate(d => d.open))) await p.locator('#settings-panel summary').click();
  await p.fill('#ver', 'v1.7');
  await p.reload(); 
  check(await p.inputValue('#ver') === 'v1.6', 'after a reload the field starts from the bundled pack again');
  check(errs.length === 0, 'no page errors ' + errs.join(' | '));
  await b.close(); process.exit(fails ? 1 : 0); })();
