#!/usr/bin/env bash
# ---------------------------------------------------------------
# AGENT-ONLY -- safe to delete outside of agents/* branches.
#
# Installs Clojure test dependencies in Claude Code Web environments
# where repo.clojars.org is blocked by the egress proxy.
#
# What it does:
#   1. Ensures lein is installed (via apt if needed)
#   2. Creates profiles.clj to disable plugins/prep-tasks and
#      exclude dev/ from source-paths
#   3. Creates stub JARs for Clojars-only deps that aren't loaded
#      during JVM tests (satisfies Maven resolution only)
#   4. Downloads real source from GitHub for libraries that ARE
#      loaded during JVM test compilation
#   5. Adds Maven Central transitive deps to profiles.clj
#
# Usage:
#   bash .agent-workarounds/clojars-deps/install-test-deps.sh
#
# Prerequisites:
#   - Maven proxy should be running (see maven-proxy/)
#   - Java and jar command must be available
#   - curl and tar must be available
#
# Idempotent: safe to run multiple times.
# ---------------------------------------------------------------

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
M2_REPO="$HOME/.m2/repository"
TMP_DIR="/tmp/clojars-deps-$$"

# --- colors for output --------------------------------------------------------
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()  { echo -e "${GREEN}[clojars-deps]${NC} $*"; }
warn() { echo -e "${YELLOW}[clojars-deps]${NC} $*"; }
err()  { echo -e "${RED}[clojars-deps]${NC} $*" >&2; }

# --- cleanup ------------------------------------------------------------------
cleanup() { rm -rf "$TMP_DIR"; }
trap cleanup EXIT
mkdir -p "$TMP_DIR"

# =============================================================================
# Step 1: Ensure lein is available
# =============================================================================
ensure_lein() {
  # Prefer apt-installed lein (has bundled standalone JAR)
  if command -v /usr/bin/lein &>/dev/null; then
    log "lein found at /usr/bin/lein"
    LEIN=/usr/bin/lein
    return
  fi

  # Check if any lein is available
  if command -v lein &>/dev/null; then
    # The pre-installed /usr/local/bin/lein may need self-install
    # which fails when GitHub releases are blocked
    if lein version &>/dev/null; then
      LEIN="$(command -v lein)"
      log "lein found at $LEIN"
      return
    fi
  fi

  # Install via apt
  log "Installing lein via apt..."
  if command -v apt-get &>/dev/null; then
    apt-get update -qq && apt-get install -y -qq leiningen 2>/dev/null
    LEIN=/usr/bin/lein
    log "lein installed via apt"
  else
    err "Cannot install lein: apt-get not available"
    err "Please install leiningen manually"
    exit 1
  fi
}

# =============================================================================
# Step 2: Create profiles.clj
# =============================================================================
create_profiles() {
  local profiles="$PROJECT_ROOT/profiles.clj"

  if [ -f "$profiles" ]; then
    log "profiles.clj already exists -- checking contents"
    if grep -q ':prep-tasks' "$profiles" && grep -q ':plugins' "$profiles"; then
      log "profiles.clj looks correct, skipping"
      return
    fi
    warn "profiles.clj exists but may be incomplete -- overwriting"
  fi

  cat > "$profiles" << 'CLJ'
;; Auto-generated by .agent-workarounds/clojars-deps/install-test-deps.sh
;; This file is in .gitignore and will not be committed.
;;
;; Purpose: Allow `lein test` to run in Claude Code Web environments
;; where Clojars (repo.clojars.org) is blocked by the egress proxy.
{:user {:plugins ^:replace []
        :prep-tasks ^:replace ["javac" "compile"]
        :dependencies [[org.clojure/tools.logging "1.1.0"]
                       [net.cgrand/macrovich "0.2.1"]]}
 :dev {:source-paths ^:replace ["src/clj" "src/cljc" "src/cljs" "web/cljs"]}}
CLJ
  log "Created profiles.clj"
}

# =============================================================================
# Step 3: Create stub JARs for Clojars-only deps
# =============================================================================
create_stub() {
  local group="$1" artifact="$2" version="$3"
  local gpath="${group//\./\/}"
  local dir="$M2_REPO/$gpath/$artifact/$version"
  local jar="$dir/$artifact-$version.jar"
  local pom="$dir/$artifact-$version.pom"

  if [ -f "$jar" ] && [ -s "$jar" ]; then
    return  # already exists and non-empty
  fi

  mkdir -p "$dir"

  # Create minimal POM
  cat > "$pom" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>$group</groupId>
  <artifactId>$artifact</artifactId>
  <version>$version</version>
</project>
EOF

  # Create empty JAR (just a manifest)
  local stub_dir="$TMP_DIR/stub-jar"
  mkdir -p "$stub_dir"
  echo "Manifest-Version: 1.0" > "$stub_dir/MANIFEST.MF"
  (cd "$stub_dir" && jar cfm "$jar" MANIFEST.MF)
}

create_all_stubs() {
  log "Creating stub JARs for Clojars-only dependencies..."

  # ClojureScript / JS interop (not loaded on JVM)
  create_stub cljsjs react 16.6.0-0
  create_stub cljsjs react-dom 16.6.0-0
  create_stub cljsjs filesaverjs 1.3.3-0
  create_stub com.cognitect transit-cljs 0.8.256
  create_stub cljs-http cljs-http 0.1.45
  create_stub com.andrewmcveigh cljs-time 0.5.2

  # Clojure server-side libs (stubbed; not in test require chain)
  create_stub clj-time clj-time 0.15.0
  create_stub clj-http clj-http 3.9.1
  create_stub com.yetanalytics ring-etag-middleware 0.1.1
  create_stub garden garden 1.3.2
  create_stub io.pedestal pedestal.service 0.5.1
  create_stub io.pedestal pedestal.route 0.5.1
  create_stub io.pedestal pedestal.jetty 0.5.1
  create_stub buddy buddy-auth 1.4.1
  create_stub buddy buddy-hashers 1.2.0
  create_stub reloaded.repl reloaded.repl 0.2.3
  create_stub bidi bidi 2.0.17
  create_stub com.stuartsierra component 0.3.2
  create_stub hiccup hiccup 1.0.5
  create_stub com.draines postal 2.0.2
  create_stub environ environ 1.1.0
  create_stub pdfkit-clj pdfkit-clj 0.1.7
  create_stub vvvvalvalval datomock 0.2.0
  create_stub com.datomic datomic-free 0.9.5697
  create_stub funcool cuerdas 2.2.0
  create_stub camel-snake-kebab camel-snake-kebab 0.4.0
  create_stub org.webjars font-awesome 5.13.1

  # Dev-only deps (plugins and dev profile)
  create_stub nrepl nrepl 1.0.0
  create_stub org.nrepl incomplete 0.1.0
  create_stub binaryage devtools 0.9.10
  create_stub figwheel-sidecar figwheel-sidecar 0.5.19
  create_stub cider piggieback 0.4.0
  create_stub day8.re-frame re-frame-10x 0.3.7

  log "Stub JARs created"
}

# =============================================================================
# Step 4: Download and install real source JARs from GitHub
# =============================================================================

# Download a GitHub repo tarball with retry logic
download_github_tarball() {
  local owner="$1" repo="$2" ref="$3" output="$4"
  local url="https://api.github.com/repos/$owner/$repo/tarball/$ref"
  local attempt=0
  local max_attempts=4
  local delay=2

  while [ $attempt -lt $max_attempts ]; do
    attempt=$((attempt + 1))
    local status
    status=$(curl -sL -o "$output" -w "%{http_code}" \
      -H "Accept: application/vnd.github+json" "$url" 2>/dev/null)

    if [ "$status" = "200" ] && [ -s "$output" ]; then
      return 0
    fi

    if [ $attempt -lt $max_attempts ]; then
      warn "Download attempt $attempt failed (HTTP $status), retrying in ${delay}s..."
      sleep $delay
      delay=$((delay * 2))
    fi
  done

  err "Failed to download $owner/$repo@$ref after $max_attempts attempts"
  return 1
}

# Build a JAR from extracted source and install to Maven repo
install_source_jar() {
  local group="$1" artifact="$2" version="$3" src_subdir="$4" extract_dir="$5"
  local gpath="${group//\./\/}"
  local dest_dir="$M2_REPO/$gpath/$artifact/$version"
  local dest_jar="$dest_dir/$artifact-$version.jar"
  local dest_pom="$dest_dir/$artifact-$version.pom"

  mkdir -p "$dest_dir"

  # Find the extracted directory (GitHub tarballs have owner-repo-hash/ prefix)
  local src_root
  src_root=$(find "$extract_dir" -maxdepth 1 -type d -name '*' | tail -1)

  if [ ! -d "$src_root/$src_subdir" ]; then
    err "Source directory $src_subdir not found in extracted tarball"
    return 1
  fi

  # Build JAR from source
  (cd "$src_root/$src_subdir" && jar cf "$dest_jar" .)

  # Create POM
  cat > "$dest_pom" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>$group</groupId>
  <artifactId>$artifact</artifactId>
  <version>$version</version>
</project>
EOF

  local count
  count=$(jar tf "$dest_jar" | grep -cE '\.(clj|cljc|cljs)$' || true)
  log "Installed $group:$artifact:$version ($count source files)"
}

install_real_deps() {
  log "Downloading real source for libraries needed at compile time..."

  # --- re-frame 0.10.9 ---
  # Required by: template.cljc, options.cljc (unconditional require)
  local rf_jar="$M2_REPO/re-frame/re-frame/0.10.9/re-frame-0.10.9.jar"
  if [ -f "$rf_jar" ] && jar tf "$rf_jar" 2>/dev/null | grep -q 'core.cljc'; then
    log "re-frame already has real source, skipping"
  else
    local rf_dir="$TMP_DIR/re-frame"
    mkdir -p "$rf_dir"
    download_github_tarball "day8" "re-frame" "v0.10.9" "$rf_dir/re-frame.tar.gz"
    (cd "$rf_dir" && tar xzf re-frame.tar.gz)
    install_source_jar "re-frame" "re-frame" "0.10.9" "src" "$rf_dir"
  fi

  # --- reagent 0.7.0 ---
  # Required by: components.cljc (unconditional require)
  local rg_jar="$M2_REPO/reagent/reagent/0.7.0/reagent-0.7.0.jar"
  if [ -f "$rg_jar" ] && jar tf "$rg_jar" 2>/dev/null | grep -q 'core.clj'; then
    log "reagent already has real source, skipping"
  else
    local rg_dir="$TMP_DIR/reagent"
    mkdir -p "$rg_dir"
    download_github_tarball "reagent-project" "reagent" "v0.7.0" "$rg_dir/reagent.tar.gz"
    (cd "$rg_dir" && tar xzf reagent.tar.gz)
    install_source_jar "reagent" "reagent" "0.7.0" "src" "$rg_dir"
  fi

  # --- macrovich 0.2.1 ---
  # Transitive dep of reagent; required at macro-expansion time
  local mv_jar="$M2_REPO/net/cgrand/macrovich/0.2.1/macrovich-0.2.1.jar"
  if [ -f "$mv_jar" ] && jar tf "$mv_jar" 2>/dev/null | grep -q 'macrovich.cljc'; then
    log "macrovich already has real source, skipping"
  else
    local mv_dir="$TMP_DIR/macrovich"
    mkdir -p "$mv_dir"
    # macrovich has no version tags; use master
    download_github_tarball "cgrand" "macrovich" "master" "$mv_dir/macrovich.tar.gz"
    (cd "$mv_dir" && tar xzf macrovich.tar.gz)
    install_source_jar "net.cgrand" "macrovich" "0.2.1" "src" "$mv_dir"
  fi
}

# =============================================================================
# Step 5: Verify
# =============================================================================
verify() {
  log "Verifying setup..."

  # Check that lein can resolve deps
  if (cd "$PROJECT_ROOT" && $LEIN classpath &>/dev/null); then
    log "lein classpath resolves successfully"
  else
    warn "lein classpath failed -- some deps may still be missing"
    warn "Run: cd $PROJECT_ROOT && $LEIN test :only orcpub.dnd.e5.ac-test"
    warn "and check error output for missing namespaces"
    return 1
  fi

  log "Setup complete. Run tests with:"
  log "  $LEIN test                                    # all tests"
  log "  $LEIN test :only orcpub.dnd.e5.ac-test        # AC tests only"
}

# =============================================================================
# Main
# =============================================================================
main() {
  log "Setting up Clojure test dependencies for Claude Code Web..."
  log "Project root: $PROJECT_ROOT"
  log ""

  ensure_lein
  create_profiles
  create_all_stubs
  install_real_deps
  verify

  log ""
  log "Done. Dependencies installed for offline test execution."
}

main "$@"
