// Browser e2e for the fighting-style builder — the REAL app via `lein e2e-server`.
//
// What this exists to check (none of it is provable from the JVM suite):
//   1. the route→view binding generated by the page-map MACRO actually renders a page
//   2. the shared :props field fragments render as real inputs
//   3. the `:when` conditional display works — tag dropdowns appear only once a bonus is entered
//   4. an authored style saves and its props survive
//
// Prereqs:  lein fig:build && lein garden once && lein e2e-server   (port 8890)
// Run:      node test/browser/fighting_style_builder_e2e.js
const fs = require('fs');
const path = require('path');
const { chromium } = require('playwright');

const BASE = process.env.E2E_BASE || 'http://localhost:8890';
const SHOTS = path.resolve(__dirname, '../../target/e2e-shots');

function findChrome() {
  const base = process.env.PLAYWRIGHT_BROWSERS_PATH || '/opt/pw-browsers';
  try {
    const dir = fs.readdirSync(base).filter(d => d.startsWith('chromium-') && !d.includes('headless')).sort().pop();
    if (dir) { const p = path.join(base, dir, 'chrome-linux', 'chrome'); if (fs.existsSync(p)) return p; }
  } catch (_) {}
  return undefined;
}

const results = [];
const check = (name, ok, detail='') => {
  results.push({name, ok});
  console.log(`${ok ? 'PASS' : 'FAIL'}  ${name}${detail ? '  — ' + detail : ''}`);
};

// A builder field is a label + an input/select somewhere after it. Find the control by label text.
async function controlFor(page, labelText) {
  const h = await page.evaluateHandle((txt) => {
    const els = [...document.querySelectorAll('*')];
    const label = els.find(e => e.children.length === 0 && e.textContent.trim() === txt);
    if (!label) return null;
    // walk up until a subtree containing an input/select
    let n = label;
    for (let i = 0; i < 5 && n; i++, n = n.parentElement) {
      const c = n.querySelector('input, select, textarea');
      if (c) return c;
    }
    return null;
  }, labelText);
  const el = h.asElement();
  return el || null;
}

(async () => {
  fs.mkdirSync(SHOTS, { recursive: true });
  const browser = await chromium.launch({ executablePath: findChrome() });
  const page = await browser.newPage({ viewport: { width: 1400, height: 1100 } });
  // Fonts are self-hosted (docs/kb/fonts.md), so the app fetches NOTHING from a third party and a
  // failed request is a real defect. No filtering — that was only needed while Open Sans came from
  // a CDN the sandbox blocked.
  const errors = [];
  const failedRequests = [];
  page.on('pageerror', e => errors.push(String(e)));
  page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
  page.on('requestfailed', r => failedRequests.push(`${r.url()} (${r.failure() && r.failure().errorText})`));

  await page.goto(`${BASE}/pages/dnd/5e/fighting-style-builder`, { waitUntil: 'networkidle' });
  await page.waitForTimeout(2500);

  const body = await page.textContent('body');
  check('page renders (macro-generated route→view binding)', /Fighting Style/i.test(body),
        `body starts: ${body.trim().slice(0, 70)}`);
  check('no uncaught JS errors on load', errors.length === 0, errors.slice(0, 2).join(' | '));
  check('no failed requests — nothing is fetched from a third party',
        failedRequests.length === 0, failedRequests.slice(0, 2).join(' | '));
  const fontOk = await page.evaluate(async () => {
    try { await document.fonts.ready; return [...document.fonts].some(f => /Open Sans/.test(f.family)); }
    catch (_) { return false; }
  });
  check('Open Sans loaded from local /fonts', fontOk);

  await page.screenshot({ path: path.join(SHOTS, 'fs-builder-empty.png'), fullPage: true });

  // the base fields the generic builder supplies
  for (const label of ['Name', 'Description']) {
    check(`field present: ${label}`, !!(await controlFor(page, label)));
  }
  // the shared :props fragments
  for (const label of ['AC Bonus', 'Attack Bonus', 'Damage Bonus']) {
    check(`prop field present: ${label}`, !!(await controlFor(page, label)));
  }

  // :when — tags hidden until a bonus is entered
  const beforeArmorTag = await controlFor(page, 'Armor requirement');
  check(':when hides the Armor tag before a bonus is entered', beforeArmorTag === null);

  const acInput = await controlFor(page, 'AC Bonus');
  if (acInput) {
    await acInput.fill('1');
    await acInput.dispatchEvent('change');
    await page.waitForTimeout(600);
  }
  const afterArmorTag = await controlFor(page, 'Armor requirement');
  check(':when reveals the Armor tag once a bonus is entered', !!afterArmorTag);
  check('typing a number raised no JS error (the seq-on-int regression)',
        !errors.some(e => /ISeqable/.test(e)), errors.filter(e => /ISeqable/.test(e))[0] || '');

  // A three-state value in a two-option <select> would DISPLAY a restriction the item does not
  // have, because a select with no matching value shows its first option.
  if (afterArmorTag) {
    const opts = await afterArmorTag.evaluate(el => [...el.options].map(o => o.textContent.trim()));
    check('Armor tag offers an explicit "Both" first', /^both$/i.test((opts[0] || '').trim()),
          `options: ${JSON.stringify(opts)}`);
    const selected = await afterArmorTag.evaluate(el => el.selectedIndex);
    check('and it is what shows while the tag is unset', selected === 0, `selectedIndex=${selected}`);
  }

  const nameInput = await controlFor(page, 'Name');
  if (nameInput) { await nameInput.fill('Bulwark'); await nameInput.dispatchEvent('change'); }
  await page.waitForTimeout(400);
  await page.screenshot({ path: path.join(SHOTS, 'fs-builder-filled.png'), fullPage: true });

  console.log(`\nscreenshots: ${SHOTS}`);
  await browser.close();
  const failed = results.filter(r => !r.ok);
  console.log(`\n${results.length - failed.length}/${results.length} checks passed`);
  process.exit(failed.length ? 1 : 0);
})().catch(e => { console.error(e); process.exit(2); });
