#!/usr/bin/env bash
# ---------------------------------------------------------------
# AGENT-ONLY -- safe to delete outside of agents/* branches.
#
# Sets up a local auth-injection proxy for Maven and Gradle, then
# starts it in the background.  Works around the Claude Code Web
# egress proxy auth issue.
#
# Usage:  source .agent-workarounds/maven-proxy/setup-maven-proxy.sh
#   or:   bash   .agent-workarounds/maven-proxy/setup-maven-proxy.sh
#
# Source: https://github.com/anthropics/claude-code/issues/13372#issuecomment-3685454645
# ---------------------------------------------------------------

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROXY_PY="$SCRIPT_DIR/maven-proxy.py"
LOCAL_PORT=3128

# --- guard: only relevant when an upstream proxy exists ----------
if [ -z "${https_proxy:-}" ] && [ -z "${HTTPS_PROXY:-}" ]; then
  echo "[proxy-setup] No https_proxy set -- skipping proxy setup."
  exit 0
fi

# =================================================================
# Maven  (~/.m2/settings.xml)
# =================================================================
MAVEN_SETTINGS="$HOME/.m2/settings.xml"
mkdir -p "$HOME/.m2"

if [ -f "$MAVEN_SETTINGS" ]; then
  echo "[proxy-setup] $MAVEN_SETTINGS already exists -- not overwriting."
  echo "[proxy-setup] Ensure it contains a proxy entry for 127.0.0.1:$LOCAL_PORT"
else
  cat > "$MAVEN_SETTINGS" <<XML
<settings>
  <!-- Auto-generated by .agent-workarounds/maven-proxy/setup-maven-proxy.sh -->
  <proxies>
    <proxy>
      <id>agent-local-proxy</id>
      <active>true</active>
      <protocol>https</protocol>
      <host>127.0.0.1</host>
      <port>${LOCAL_PORT}</port>
    </proxy>
  </proxies>
</settings>
XML
  echo "[proxy-setup] Wrote $MAVEN_SETTINGS"
fi

# =================================================================
# Gradle  (~/.gradle/gradle.properties)
# =================================================================
GRADLE_PROPS="$HOME/.gradle/gradle.properties"
mkdir -p "$HOME/.gradle"

GRADLE_MARKER="# agent-local-proxy"

if [ -f "$GRADLE_PROPS" ] && grep -q "$GRADLE_MARKER" "$GRADLE_PROPS" 2>/dev/null; then
  echo "[proxy-setup] $GRADLE_PROPS already has proxy entries -- not overwriting."
else
  cat >> "$GRADLE_PROPS" <<PROPS

$GRADLE_MARKER
# Auto-generated by .agent-workarounds/maven-proxy/setup-maven-proxy.sh
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=${LOCAL_PORT}
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=${LOCAL_PORT}
PROPS
  echo "[proxy-setup] Appended proxy config to $GRADLE_PROPS"
fi

# =================================================================
# Start the local proxy
# =================================================================
if lsof -i ":$LOCAL_PORT" >/dev/null 2>&1; then
  echo "[proxy-setup] Port $LOCAL_PORT already in use -- assuming proxy is running."
  exit 0
fi

python3 "$PROXY_PY" &
PROXY_PID=$!
echo "[proxy-setup] Started maven-proxy.py (PID $PROXY_PID) on 127.0.0.1:$LOCAL_PORT"
