(ns orcpub.dnd.e5.portrait-calibration
  "Per-piece portrait calibration, read from resources/portrait-pack at BUILD
   time and inlined, so the server and the browser bundle carry the same data
   and nothing is fetched at runtime.

     loom.edn    what the Loom places (irises, pupils, lids, whites) --
                 generated by `lein run -m orcpub.portrait-pack.import`
     pieces.edn  choices that are ours (shadows, lips, gamma) -- hand-edited

   Both are {layer {\"file.png\" {field value}}}; pieces.edn wins where they
   overlap. Changing either needs a rebuild, as any code change does."
  (:require [clojure.edn :as edn]
            [clojure.java.io :as io]))

(def files ["portrait-pack/loom.edn" "portrait-pack/pieces.edn"])

(defn read-file [path]
  (if-let [r (io/resource path)]
    (edn/read-string (slurp r))
    {}))

(defn merged
  "loom.edn under pieces.edn, merged per piece."
  []
  (apply merge-with (fn [a b] (merge-with merge a b)) (map read-file files)))

(defmacro calibration
  "The merged calibration, as a literal."
  []
  (merged))
