import { test, expect } from '@playwright/test';

// A3 follow-up: the "Save anyway" remediation is auto-generated by
// reg-save-homebrew for every builder it registers, but the Selection builder is
// standalone (it has bespoke option-name checks), so it needed the hatch wired in
// explicitly. Proves an imperfect selection (name only, no option source) can be
// forced into My Content with placeholders instead of being trapped in the builder.

const NAME_INPUT = '.field:has(.personality-label span:text-is("Name")) input';

test('A3 Save anyway: an imperfect selection lands in My Content', async ({ page }) => {
  await page.goto('/pages/dnd/5e/selection-builder', { waitUntil: 'load' });
  const name = page.locator(NAME_INPUT).first();
  await expect(name).toBeVisible({ timeout: 30000 });
  await name.fill('A3 Anyway Selection'); // name only, no option source -> save fails

  await page.locator('button:has-text("Save to Browser Storage"):not(#sticky-header button)')
    .first().click();

  // the save-failure banner offers the remediating hatch (renders twice — hidden
  // #header-container copy first, visible one last).
  const anyway = page.getByText('Save anyway with placeholders', { exact: true }).last();
  await expect(anyway).toBeVisible({ timeout: 10000 });
  await anyway.click();
  await page.waitForTimeout(500);

  const plugins = await page.evaluate(() => localStorage.getItem('plugins'));
  expect(plugins ?? '', 'imperfect selection is now in My Content (plugins)')
    .toContain('A3 Anyway Selection');
  // landed under the placeholder source, as a selection
  expect(plugins ?? '', 'placeholder option source applied').toContain('Unsorted Homebrew');
  expect(plugins ?? '', 'stored as a selection').toContain(':orcpub.dnd.e5/selections');
});
