name: Continuous Integration

on: [pull_request]

jobs:
  lint:
    name: Run Linter and Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8.0.292
      - name: Load pdfbox from /lib
        run: mkdir ~/.m2/repository/ && mkdir ~/.m2/repository/org/ && cp -rv ./lib/* ~/.m2/repository
      - name: ls .m2
        run: ls -la ~/.m2/repository/org/
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@11.0
        with:
          # Install just one or all simultaneously
          cli: 1.10.1.693 # Clojure CLI based on tools.deps
          lein: 2.9.1     # or use 'latest' to always provision latest version of leiningen
          boot: 2.8.3     # or use 'latest' to always provision latest version of boot
      - name: Get leiningen version
        run: lein -v
      - name: Lint
        run: |
          # Force lein to download the clj-kondo dependency
          lein with-profile lint deps :tree

          # Find the exact path to the clj-kondo uberjar
          CLJ_KONDO_PATH=$(find ~/.m2/repository/clj-kondo -name "*standalone.jar")
          echo "Found clj-kondo at: $CLJ_KONDO_PATH"

          # Run clj-kondo directly using the uberjar
          java -jar $CLJ_KONDO_PATH --lint src
          EXIT_CODE=$?
          echo "Linter exited with code: $EXIT_CODE"

          if [ $EXIT_CODE -eq 0 ] || [ $EXIT_CODE -eq 2 ]; then
            echo "Success or warnings only, passing build."
            exit 0
          else
            echo "Error detected (exit code $EXIT_CODE), failing build."
            exit 1
          fi
      - name: Run tests
        run: lein test
